name: mi_iot_token
description: A Flutter package for xiaomi iot token extract.
version: 0.1.0
homepage: https://github.com/i2Echo/mi_iot_token

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.2
  http: ^0.13.5
  universal_io: ^2.2.0

dev_dependencies:
  # Writing and running Dart tests.
  test: ^1.22.2